# Generated by Django 3.0.7 on 2020-06-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
