# Generated by Django 3.0.7 on 2020-06-19 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'contact us'},
        ),
    ]
