# Generated by Django 3.0.7 on 2020-06-16 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20200616_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chefs',
            options={'verbose_name': 'chef', 'verbose_name_plural': 'chefs'},
        ),
    ]
