# Generated by Django 3.0.7 on 2020-06-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20200616_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefs',
            name='bio',
            field=models.CharField(max_length=500),
        ),
    ]
