# Generated by Django 3.0.7 on 2020-06-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='message',
            field=models.CharField(max_length=1000),
        ),
    ]
