# Generated by Django 3.0.7 on 2020-06-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20200616_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='message',
            field=models.TextField(),
        ),
    ]
